Repository SpiNNakerManchester/SpiNNaker_PDP2, pull requests merged in 2022-03, with the labels that each got.

#48 turn off xml validation
  .github/workflows/python_actions.yml
Labels: bug

#50 Global data new
  spinn_pdp2/input_vertex.py
  spinn_pdp2/mlp_network.py
  spinn_pdp2/sum_vertex.py
  spinn_pdp2/threshold_vertex.py
  spinn_pdp2/weight_vertex.py
Labels: enhancement

#55 Synchronisation redesign
  .gitignore
  c_code/comms_i.c
  c_code/comms_i.h
  c_code/comms_s.c
  c_code/comms_s.h
  c_code/comms_t.c
  c_code/comms_t.h
  c_code/comms_w.c
  c_code/comms_w.h
  c_code/init_i.c
  c_code/init_i.h
  c_code/init_s.c
  c_code/init_s.h
  c_code/init_t.c
  c_code/init_t.h
  c_code/init_w.c
  c_code/init_w.h
  c_code/input.c
  c_code/mlp_externs.h
  c_code/mlp_params.h
  c_code/mlp_types.h
  c_code/process_i.c
  c_code/process_i.h
  c_code/process_s.c
  c_code/process_s.h
  c_code/process_t.c
  c_code/process_t.h
  c_code/process_w.c
  c_code/process_w.h
  c_code/sum.c
  c_code/threshold.c
  c_code/weight.c
  examples/README.md
  examples/simple_past_tense/simple_past_tense.ex
  examples/simple_past_tense/simple_past_tense.py
  examples/simple_past_tense/simple_past_tense_weights.txt
  spinn_pdp2/input_vertex.py
  spinn_pdp2/mlp_network.py
  spinn_pdp2/mlp_types.py
  spinn_pdp2/sum_vertex.py
  spinn_pdp2/threshold_vertex.py
  spinn_pdp2/weight_vertex.py
Labels: bug, enhancement
